name: kimo_clean
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_secure_storage: ^10.0.0
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true